# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ab931ffe06b34bc4abf6322922ded1583188ea7dddb216f2b5283c1674ad8ed0b2b8b5aa9b001041075a7af0474f94f917ff7f1bf71c65a145fb3024a77828b

test:
  secret_key_base: c3e8b40288898484a50bc071c550dd22ba76f921c927969ade5093cd72e36b828e9b3a1453113e6950f3aee011e465334730ef0c86187ae9e4e0220a93f12c0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
